### ISSUE TITLE
Make the animations configurable

### ISSUE THREAD

**Issue by mpacer** [michaelpacer/hiding_tags_nbconvert#2]
each option in 

```css
:root{
    --in-time: .5s;
    --out-time: .5s;
    --max-height-small: 0px;
    --max-height-big: 5000px;
    --transition-path-out: cubic-bezier(0, 0.67, 0.36, 1);
    --transition-path-in: ease-in-out;
    --padding-hidden: 0px;
} 
```

should be made a configurable string.
